In [2]:
import numpy as np
import pandas as pd

In [3]:
file1='AAPL.csv'
data=pd.read_csv(file1)
data

,1stJuly,6thJuly,7thJuly,8th July,13thJuly,20thJuly,22thJuly,27thJuly,28thJuly
0,3201.0,3259.0,3213,3202.0,3278.0,3217.0,3257.0,3243.0,3222.0
1,3202.0,3232.0,3240,3274.0,3255.0,3259.0,3217.0,3259.0,3204.0
2,3203.0,3227.0,3215,3353.0,3217.0,3248.0,3248.0,3257.0,3239.0
3,3204.0,3204.0,3276,3273.0,3265.0,3229.0,3243.0,3219.0,3245.0
4,3205.0,3227.0,3259,3276.0,3261.0,3274.0,3229.0,3204.0,3275.0
5,3206.0,3243.0,3265,3224.0,3205.0,3221.0,3221.0,3204.0,3246.0
6,3207.0,3231.0,3258,3234.0,3229.0,3264.0,3264.0,3229.0,3225.0
7,3208.0,3264.0,3278,3215.0,3257.0,3246.0,3259.0,3210.0,3261.0
8,3209.0,3201.0,3220,3245.0,3213.0,3222.0,3246.0,3232.0,3265.0
9,3210.0,3265.0,3208,3244.0,3224.0,3231.0,3222.0,3212.0,3238.0
10,3211.0,3218.0,3277,3250.0,3235.0,3255.0,3231.0,3235.0,3256.0
11,3212.0,3233.0,3202,3255.0,3234.0,3273.0,3255.0,3255.0,3254.0
12,3213.0,3257.0,3269,3217.0,3202.0,3219.0,3273.0,3214.0,3232.0
13,3214.0,3241.0,3268,3270.0,3264.0,3257.0,3219.0,3248.0,3253.0
14,3215.0,3209.0,3236,3234.0,3206.0,3206.0,3206.0,3201.0,3214.0
15,3216.0,3325.0,3229,3260.0,3211.0,3214.0,3214.0,3250.0,3201.0
16,3217.0,3261.0,3257,3231.0,3274.0,3240.0,3240.0,3268.0,3262.0
17,3218.0,3240.0,3216,3229.0,3236.0,3268.0,3213.0,3320.0,3278.0
18,3219.0,3255.0,3212,3264.0,3212.0,3263.0,3261.0,3277.0,3231.0
19,3220.0,3222.0,3204,3203.0,3234.0,3243.0,3268.0,3216.0,3271.0
20,3221.0,3229.0,3225,3207.0,3256.0,3215.0,3263.0,3264.0,3208.0
21,3222.0,3252.0,3238,3353.0,3256.0,3261.0,3250.0,3240.0,3264.0
22,3223.0,3263.0,3251,3247.0,3209.0,3213.0,3224.0,3268.0,3243.0
23,3224.0,3251.0,3249,3257.0,3249.0,3250.0,3227.0,3231.0,3226.0
24,3225.0,3238.0,3221,3269.0,3275.0,3224.0,3278.0,3232.0,3219.0
25,3226.0,3223.0,3205,3255.0,3216.0,3227.0,3205.0,3251.0,3221.0
26,3227.0,3237.0,3241,3237.0,3219.0,3278.0,3234.0,3273.0,3321.0
27,3228.0,3226.0,3262,3277.0,3225.0,3228.0,3228.0,3254.0,3229.0
28,3229.0,3226.0,3353,3243.0,3248.0,3266.0,3271.0,3213.0,3221.0
29,3230.0,3268.0,3237,3228.0,3272.0,3205.0,3277.0,3271.0,3247.0
...,...,...,...,...,...,...,...,...,...
56,3257.0,3258.0,3231,NaN,3204.0,3209.0,3233.0,NaN,3258.0
57,3258.0,3242.0,3203,NaN,3240.0,3203.0,3218.0,NaN,3277.0
58,3259.0,3250.0,3268,NaN,3201.0,3236.0,3218.0,NaN,3249.0
59,3260.0,3208.0,3248,NaN,3238.0,3223.0,3201.0,NaN,3251.0
60,3261.0,3210.0,3263,NaN,3250.0,3237.0,3209.0,NaN,3272.0
61,3262.0,3245.0,3244,NaN,3227.0,3207.0,3203.0,NaN,3244.0
62,3263.0,3236.0,3255,NaN,3262.0,3253.0,3236.0,NaN,3240.0
63,3264.0,2254.0,3243,NaN,3252.0,NaN,3223.0,NaN,3242.0
64,3265.0,3266.0,3218,NaN,3237.0,NaN,3207.0,NaN,3215.0
65,3266.0,3278.0,3274,NaN,NaN,NaN,3253.0,NaN,3241.0
66,3267.0,3271.0,3266,NaN,NaN,NaN,NaN,NaN,3207.0
67,3268.0,3276.0,3222,NaN,NaN,NaN,NaN,NaN,3247.0
68,3269.0,3272.0,3226,NaN,NaN,NaN,NaN,NaN,3218.0
69,3270.0,3274.0,3256,NaN,NaN,NaN,NaN,NaN,3236.0
70,3271.0,3217.0,3239,NaN,NaN,NaN,NaN,NaN,3237.0
71,3272.0,3277.0,3233,NaN,NaN,NaN,NaN,NaN,3266.0
72,3273.0,NaN,3242,NaN,NaN,NaN,NaN,NaN,NaN
73,3274.0,NaN,3237,NaN,NaN,NaN,NaN,NaN,NaN
74,3275.0,NaN,3207,NaN,NaN,NaN,NaN,NaN,NaN
75,3276.0,NaN,3206,NaN,NaN,NaN,NaN,NaN,NaN
76,3277.0,NaN,3258,NaN,NaN,NaN,NaN,NaN,NaN
77,3278.0,NaN,3234,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,3213,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,3271,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,3223,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,3202,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,2224,NaN,NaN,NaN,NaN,NaN,NaN
83,NaN,NaN,3271,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,NaN,3246,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,NaN,3265,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
mat=data.to_numpy()
attendence=[]
for i in range(3201,3279):
    occurrences = np.count_nonzero(mat == i)
    attendence.append((i,occurrences))
attendence

[(3201, 9),
 (3202, 9),
 (3203, 8),
 (3204, 8),
 (3205, 10),
 (3206, 9),
 (3207, 10),
 (3208, 4),
 (3209, 8),
 (3210, 7),
 (3211, 5),
 (3212, 8),
 (3213, 9),
 (3214, 6),
 (3215, 6),
 (3216, 7),
 (3217, 6),
 (3218, 9),
 (3219, 8),
 (3220, 7),
 (3221, 11),
 (3222, 9),
 (3223, 8),
 (3224, 8),
 (3225, 7),
 (3226, 8),
 (3227, 7),
 (3228, 7),
 (3229, 9),
 (3230, 1),
 (3231, 9),
 (3232, 9),
 (3233, 7),
 (3234, 10),
 (3235, 8),
 (3236, 8),
 (3237, 10),
 (3238, 8),
 (3239, 8),
 (3240, 8),
 (3241, 8),
 (3242, 8),
 (3243, 8),
 (3244, 4),
 (3245, 6),
 (3246, 9),
 (3247, 4),
 (3248, 8),
 (3249, 8),
 (3250, 8),
 (3251, 7),
 (3252, 7),
 (3253, 5),
 (3254, 7),
 (3255, 10),
 (3256, 9),
 (3257, 10),
 (3258, 8),
 (3259, 8),
 (3260, 8),
 (3261, 9),
 (3262, 6),
 (3263, 8),
 (3264, 10),
 (3265, 9),
 (3266, 7),
 (3267, 1),
 (3268, 10),
 (3269, 8),
 (3270, 5),
 (3271, 9),
 (3272, 8),
 (3273, 6),
 (3274, 7),
 (3275, 5),
 (3276, 4),
 (3277, 9),
 (3278, 8)]

In [49]:
import csv
with open('finalJuly.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(attendence)